services:
  store_manager:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - labo03-network
    depends_on:
      - mysql
      - redis

  tests:
    build: .
    volumes:
      - .:/app
    working_dir: /app/src
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: labo03
      DB_PASSWORD: labo03
      DB_NAME: labo03_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - mysql
      - redis
    command: python -m pytest

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo03_db
      MYSQL_USER: labo03
      MYSQL_PASSWORD: labo03
    networks:
      - labo03-network
    
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - labo03-network
    

networks:
  labo03-network:
    driver: bridge
    external: true

volumes:
  mysql_data:
